name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build with buildozer-action
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: android debug
        workdir: .
        buildozer_version: stable

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: SmartPlanner-APK
        path: ${{ steps.buildozer.outputs.filename }}
        retention-days: 60
